### ISSUE TITLE
Tabs - Add the possibility to receive children in Tabs

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1233]
**Is your iteration request related to a problem?**
We use tabs to navigate through different sections, but they are not links (`anchors`) but `spans` in a list, hence they can't be tracked by crawlers.

**Describe the solution you'd like**
Is there an alternative in SUI, or a planned iteration to allow `links` to be used in Tabs?
i.e.: The component Tab could have Prop to inform the type of element to use

**Additional context**
This need is very common and also requested by other teams in the company

**Comment by adriadoz** [comment]
IMHO Tab component should be able to receive children, instead of having types that build the components inside, in order to be more scalable. Because adding `type="link"` would also mean adding `href, target, title`, etc as props. And if someday we want to add a new component we would also have to add more props for every attribute. 

We could validate that the children is an instance of, for example in this case, AtomButton.

**Comment by turolopezsanabria** [comment]
Hey there, there are more cases for this need, giving extra weight to @adriadoz suggestion.
In this case, a badge counter is needed next to the Tab label.

![tab with counter](https://user-images.githubusercontent.com/23620759/96440725-a90a6080-1208-11eb-8f50-b76768b0e39c.png)

**Comment by turolopezsanabria** [comment]
hello, I've moved this one + the comments to discussions [here](https://github.com/SUI-Components/sui-components/discussions/1567) until is a true "issue"

cheers
