### ISSUE TITLE
atom/spinner: Is showing literal by default

### ISSUE THREAD

**Issue by AitorRodriguez990** [SUI-Components/sui-components#573]
When we use **AtomSpinner** component it shows a literal "Loading..." by default. Is it necessary?

```javascript
AtomSpinner.defaultProps = {
  delayed: false,
  type: TYPES.SECTION,
  loader: <SUILoader text="Loading..." />
}
```

[Source](https://github.com/SUI-Components/sui-components/blob/master/components/atom/spinner/src/index.js#L88)

If we want to remove this literal we must import AtomSpinner with a _loader_ prop value without literal:

```javascript
<AtomSpinner loader={<SUILoader />} />
```

Instead of this, it is not better remove this defaultProp and let developer choose?

**Comment by jcger** [comment]
Yes, it shouldn't be done this way, there shouldn't be any hardcoded label. But the bug is another, there shouldn't even be a prop as design didn't define a text at all, there is just the loader

Also, we should create the loader as a component by itself and remove the default loader prop as you said.

I will create an issue in our jira, please talk to me if you'll work on it

**Comment by danivm** [comment]
Because of this we had to overwrite the spinner styles:

https://github.schibsted.io/scmspain/frontend-fc--uilib-components/pull/453
