### ISSUE TITLE
atom/input: readonly prop is not set

### ISSUE THREAD

**Issue by juanmendez90** [SUI-Components/sui-components#628]
When the readOnly prop is sent the atom/input doesn't set a readOnly prop instead it set the disabled one. Is this the expected behavior?

```js
disabled={disabled || readOnly}
```

**Comment by jcger** [comment]
It is the expected behaviour

disabled: user can't write and the input shows up disabled (see `disabled` [demo](https://sui-components.now.sh/workbench/atom/input/demo))
readOnly: user can't write but the input looks active, used by one of our select variants, in which the user can't write to choose its option (see `with placeholder` [demo](https://sui-components.now.sh/workbench/molecule/select/demo))

**Comment by juanmendez90** [comment]
In the case of molecule/select, the readOnly is implicit so the input will be disabled and its value will be ignored when submitted. I also found that is not possible to set a name to it. Should I use a hidden input that stores the atom/select value?

**Comment by juanmaguitar** [comment]
Hi @juanmendez90, I answer you below...

> the readOnly is implicit so the input will be disabled and its value will be ignored when submitted.

The `MoleculeSelect` component is not really a `select` but a `div` that emulates a `select` behaviour. That's why the value of the `select` should be captured from a higher component that manages the state of the component (or the general state of the form). For that, there's a `onChange` prop that can be used to pass a handler that will be triggered on every value change (receiving that value)

> I also found that is not possible to set a name to it

For that same reason (_The `MoleculeSelect` component is not really a `select` but a `div` that emulates a `select` behaviour._) you cannot set a `name` for this component. And also for the same reason ( _the value of the `select` should be captured from a higher component that manages the state of the component_ ) you shouldn't need to set a `name` in this component, because the submit of the form should be handled programmatically by the higher component that manages the state of the whole form

**Comment by juanmendez90** [comment]
Ok got it, I will close the issue then, thanks for your answers
